In [10]:
import numpy as np

In [11]:
#num py is a python library for scientific computing.
x=[1,"python",[1,2,3,4]]

In [12]:
print(x)

[1, 'python', [1, 2, 3, 4]]


In [13]:
#numpy is fast and efficient and utilizes less space compared to list
#very useful in calculation intense task


In [14]:
#the core difference between a python list and a numpy array is that, your num py array can contain values of thr same data type.

# reasons why numpy is prefered
#it is memmory efficient ,you can control the usage of memorythrough the available data types of numpy.

#it is developed using c programmming language ,so it is cappable of performing complex computations in an efficient manner.


In [15]:
x=np.array([1,2,3,4,4])
print(type(x))
print(x)
print(x.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 4]
int64


In [16]:
#numpy arrays can store only vakues of a single data tyype.
# and in this  aspect they are similar with programming languages like c,c++,java etc
#
x=np.append(x,[1,2,3,3,4])
print(x)
x=np.append(x,"Python")
print(x)


[1 2 3 4 4 1 2 3 3 4]
['1' '2' '3' '4' '4' '1' '2' '3' '3' '4' 'Python']


In [17]:
py_list=[1,"python"]
py_arr=np.array(py_list)
py_arr[0]+"string"

'1string'

In [18]:
py_arr.size

2

In [19]:
xy=np.array([1,2,3,4,5,6,2.3,3.4,33.,234.,24,4])
print(xy.size)
print(xy.dtype)

12
float64


In [20]:
xy_int=np.array([1,2,3,4,4,5],dtype=np.int16)
print(xy_int.dtype)


int16


In [21]:
import sys
print(sys.getsizeof(xy_int))
sys.getsizeof(x)

124


1036

In [22]:
#numpy also supports multidimentional array.
y=np.array([[1,2,3,4,5,4,5],[6,4,5,7,8,9,0]])
print(y)


[[1 2 3 4 5 4 5]
 [6 4 5 7 8 9 0]]


In [23]:
y.ndim

2

In [24]:
print(y[1,3])

7


In [25]:
print(y[0:1])

[[1 2 3 4 5 4 5]]


In [26]:
y.shape

(2, 7)

In [27]:
d2=np.array([[1,2,3,4,5,5,4],[22,3,4,5,6,78,8]])
d2

array([[ 1,  2,  3,  4,  5,  5,  4],
       [22,  3,  4,  5,  6, 78,  8]])

In [28]:
y+d2

array([[ 2,  4,  6,  8, 10,  9,  9],
       [28,  7,  9, 12, 14, 87,  8]])

In [29]:
y-d2

array([[  0,   0,   0,   0,   0,  -1,   1],
       [-16,   1,   1,   2,   2, -69,  -8]])

In [30]:
y*d2  #it is not performing matrix multiplication but only an element eise multiplication

array([[  1,   4,   9,  16,  25,  20,  20],
       [132,  12,  20,  35,  48, 702,   0]])

In [31]:
print(y/d2) # it does not give matrix division but an element wise division


[[1.         1.         1.         1.         1.         0.8
  1.25      ]
 [0.27272727 1.33333333 1.25       1.4        1.33333333 0.11538462
  0.        ]]


In [32]:
y.T

array([[1, 6],
       [2, 4],
       [3, 5],
       [4, 7],
       [5, 8],
       [4, 9],
       [5, 0]])

In [33]:
#the sape return a single value tuple for 1-d  tupe of 

In [34]:
# a range method is similar to the range in python 
x=np.arange(10)

In [35]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
x=np.arange(1,9)
print(x)

[1 2 3 4 5 6 7 8]


In [37]:
x=np.arange(8,2,-1)
print(x)

[8 7 6 5 4 3]


In [38]:
#now e can continue with linspace functions
linspace_arr=np.linspace(4,5,8)
print(linspace_arr)
# rethurn an array of elements which are evenly distributed between 4 and 5 .both the start and end points are present in your array.

[4.         4.14285714 4.28571429 4.42857143 4.57142857 4.71428571
 4.85714286 5.        ]


In [39]:
linspace_arr=np.linspace(4,6,8)#this functions create an array consisting of 8  elements including the starting and ending element will be present 
# to to make 8 equal parts we will divide by 7  ...ie 8-1 ...and 
# the value of the elements are equally distant from each other..so here 6-4 =2 willl be divided into 7 equal parts and will be added to the 
# startinf element that is 4 ...so that every element in the array will be equally distant from each other
print(linspace_arr)

[4.         4.28571429 4.57142857 4.85714286 5.14285714 5.42857143
 5.71428571 6.        ]


In [40]:
arr=np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
#now we will be discussing about the reshape method 
single_dim=np.arange(12)
print(single_dim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
single_dim.shape

(12,)

In [43]:
print(single_dim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
y=single_dim.reshape(3,4)

In [45]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
single_dim.reshape(6,2)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
single_dim #the reshape does not permanantly affect or change the original array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
y.min()

np.int64(0)

In [49]:
y.max()

np.int64(11)

In [50]:
x=np.arange(6)
x=x.reshape(2,3)
print(x)


[[0 1 2]
 [3 4 5]]


In [51]:
x.sum()

np.int64(15)

In [52]:
x.sum(axis=0)#note if axis=0 means along x axis

array([3, 5, 7])

In [53]:
x.sum(axis=1) # axis=1 means alomg y axis

array([ 3, 12])

In [54]:
x.min(axis=0)

array([0, 1, 2])

In [55]:
x.max(axis=1)

array([2, 5])

In [56]:
#argmax(),argmin(),argsort()
d1=np.array([1,4,8,3,6,8,32,2])
d1.argmax()

np.int64(6)

In [57]:
d1.argmin()

np.int64(0)

In [58]:
d1.argsort()

array([0, 7, 3, 1, 4, 2, 5, 6])

In [59]:
x=np.array([[1,22,33],[51,6,7]])
print(x)

[[ 1 22 33]
 [51  6  7]]


In [60]:
x.argmax(axis=1)

array([2, 0])

In [61]:
x.argmax(axis=0)

array([1, 0, 0])

In [62]:
x=np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [63]:
x.ravel() #just makes amultudimentional array into a single dimentional array


array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [64]:
print(x.ravel())

[1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]


In [65]:
x=np.arange(0,9)
print(x)
p=x.reshape(3,3)

[0 1 2 3 4 5 6 7 8]


In [66]:
y=np.arange(9,18)
q=y.reshape(3,3)

In [67]:
print(p@q)#it is used to do matrix multiplication

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [68]:
p@q

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [69]:
np.sin(p)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [70]:
np.cosh(p)

array([[1.00000000e+00, 1.54308063e+00, 3.76219569e+00],
       [1.00676620e+01, 2.73082328e+01, 7.42099485e+01],
       [2.01715636e+02, 5.48317035e+02, 1.49047916e+03]])

In [71]:
print(p)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
np.where(p>5)

(array([2, 2, 2]), array([0, 1, 2]))

In [72]:
sample=np.arange(16).reshape(4,4)

In [73]:
print(sample)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [77]:
np.where(sample>6)

(array([1, 2, 2, 2, 2, 3, 3, 3, 3]), array([3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [78]:
np.nonzero(sample)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))