In [4]:
import pandas as pd

In [2]:
#pandas is a open source  python library used easen the process of data analysis and  data visualization using python .
#it is derived from "danel data".An econometrics term which is used to refer multidimentional data .

#pandas provide two basic data structures:that is .Series and Data frame structures.


#apanda sereis data structure is a one dimentional labeled array .
#so it can consist only if elements if a single data type .

#A panda series object is size immutable.But,yiou can mpdify the individual elements present in your object 


In [4]:
#a data frame is a two dimentional data structure ,labeled tabular structure which  is size mutable ,since it is  tabular structure it is similar to 
# exel sheets .

In [6]:
data =["steve","35","Male","3.5"]
series_obj=pd.Series(data)
print(series_obj)

0    steve
1       35
2     Male
3      3.5
dtype: object


In [7]:
data[0]

'steve'

In [8]:
data[2]

'Male'

In [9]:
series_obj[0]

'steve'

In [10]:
series_obj.index=["name","age","gender","rating"]

In [11]:
series_obj["name"]

'steve'

In [12]:
import numpy as np

In [14]:
obj2=pd.Series([1,2,3,4,5,5],dtype=np.int32)

In [15]:
print(obj2)

0    1
1    2
2    3
3    4
4    5
5    5
dtype: int32


In [16]:
#data frames

In [17]:
data={
    "name":["jobin","nihal","rohith","jerrit"],
    "age":[32,24,53,34],
    "gender":["M","F","M","M"],
    "rating":[4.5,3.5,2.4,5.3]
}

In [18]:
df=pd.DataFrame(data)

In [19]:
print(df)

     name  age gender  rating
0   jobin   32      M     4.5
1   nihal   24      F     3.5
2  rohith   53      M     2.4
3  jerrit   34      M     5.3


In [20]:
print(df.name)

0     jobin
1     nihal
2    rohith
3    jerrit
Name: name, dtype: object


In [21]:
print(df.gender)

0    M
1    F
2    M
3    M
Name: gender, dtype: object


In [22]:
print(df.age)

0    32
1    24
2    53
3    34
Name: age, dtype: int64


In [23]:
print(df.rating)

0    4.5
1    3.5
2    2.4
3    5.3
Name: rating, dtype: float64


In [24]:
#the series data type consist of  homogeneous values .we cannot alter the size of the series but can alter the values of the series 

# but in data frame consists of heterogeneous values .you can alter the size of the data frame/
# you can modify the data present in your dataframe 


In [25]:
print(df)

     name  age gender  rating
0   jobin   32      M     4.5
1   nihal   24      F     3.5
2  rohith   53      M     2.4
3  jerrit   34      M     5.3


In [26]:
df.index=["first","second","third","fourth"]

In [27]:
print(df)

          name  age gender  rating
first    jobin   32      M     4.5
second   nihal   24      F     3.5
third   rohith   53      M     2.4
fourth  jerrit   34      M     5.3


In [28]:
print(df["age"].values)#gives an numpy array of the values present in my colum age 

[32 24 53 34]


In [33]:
print(df["name"].values)#gives an numpy array of the values present in my column name 

['jobin' 'nihal' 'rohith' 'jerrit']


In [31]:
print(df["rating"].values.dtype)#gives the data type of the column values .

float64


In [35]:
print(df["name"].values.dtype)#gives the data type of the column name

object


In [36]:
df.index

Index(['first', 'second', 'third', 'fourth'], dtype='object')

In [38]:
df.index[0]

'first'

In [39]:
print(series_obj)

name      steve
age          35
gender     Male
rating      3.5
dtype: object


In [40]:
print(series_obj.shape)

(4,)


In [41]:
df.shape

(4, 4)

In [42]:
#.size give sthe total number of elements in your object 
series_obj.size

4

In [43]:
series_obj.ndim  #.ndim gives the dimention of the data frame 

1

In [44]:
df.ndim

2

In [77]:
df=pd.DataFrame(np.random.randn(15,4),columns=list('ABCD'))

In [78]:
print(df)

           A         B         C         D
0  -2.527221 -1.045132 -1.622769 -0.757051
1   2.836031 -0.095831  0.599223 -0.641949
2   0.866606  0.254359  0.397553 -0.577572
3   0.290957 -0.469696  0.463944 -1.142226
4   0.018912  1.773219 -0.279434  0.919145
5   1.607530 -0.287011  0.080230 -1.249833
6  -0.296463 -0.376051  0.933423  0.442643
7  -1.320294  0.440962  0.968697  1.392849
8   0.493802 -0.570522 -1.714255 -0.269707
9  -0.377591 -1.667361  0.474226 -0.035509
10  0.323350  1.102024 -0.971712  1.083578
11 -1.322506  0.143315 -0.909598  0.415461
12  0.232145  0.718343  0.761527  0.901154
13  0.421787  0.089221 -0.009078  0.180910
14 -0.107209 -0.735749 -0.476159  1.306162


In [79]:
print("data types: \n",df.dtypes)
print("index:",df.index)
print("columns",df.columns)
print("values")
print(df.values)
print("shape:",df.shape)
print("size:",df.size)#give the number of elements in your data frame 
print("dimention:",df.ndim)
print("is empty:",df.empty)


data types: 
 A    float64
B    float64
C    float64
D    float64
dtype: object
index: RangeIndex(start=0, stop=15, step=1)
columns Index(['A', 'B', 'C', 'D'], dtype='object')
values
[[-2.52722064 -1.04513215 -1.62276869 -0.75705071]
 [ 2.8360314  -0.09583109  0.59922273 -0.64194892]
 [ 0.86660594  0.25435929  0.39755276 -0.5775721 ]
 [ 0.29095712 -0.46969601  0.4639443  -1.14222636]
 [ 0.01891192  1.77321937 -0.27943428  0.91914524]
 [ 1.60752959 -0.28701121  0.08022973 -1.24983334]
 [-0.29646307 -0.3760508   0.93342294  0.44264267]
 [-1.32029421  0.44096235  0.96869701  1.39284946]
 [ 0.49380193 -0.57052242 -1.71425453 -0.2697068 ]
 [-0.37759094 -1.66736052  0.47422603 -0.0355093 ]
 [ 0.32334952  1.10202352 -0.97171225  1.08357816]
 [-1.32250586  0.14331483 -0.90959801  0.41546051]
 [ 0.23214522  0.71834275  0.76152715  0.90115429]
 [ 0.42178744  0.08922054 -0.00907751  0.18090979]
 [-0.10720878 -0.73574948 -0.47615854  1.3061621 ]]
shape: (15, 4)
size: 60
dimention: 2
is empty: Fals

In [80]:
print(df.dtypes)

A    float64
B    float64
C    float64
D    float64
dtype: object


In [81]:
#there are some common Series and Data Frame methods

series_obj=pd.Series(data=np.arange(7),index=np.random.randn(7))
print(series_obj)

 0.075751    0
-0.178983    1
-0.785924    2
 0.024129    3
 0.064774    4
-1.752693    5
-0.819773    6
dtype: int64


In [82]:
series_obj[series_obj.index[0]]

np.int64(0)

In [83]:
series_obj[series_obj.index[1]]#index value must be either string or int .d=so if it is not do thriygh this method.

np.int64(1)

In [84]:
series_obj.head(1)

0.075751    0
dtype: int64

In [85]:
series_obj.head()

 0.075751    0
-0.178983    1
-0.785924    2
 0.024129    3
 0.064774    4
dtype: int64

In [86]:
df.head()

A         B         C         D
0 -2.527221 -1.045132 -1.622769 -0.757051
1  2.836031 -0.095831  0.599223 -0.641949
2  0.866606  0.254359  0.397553 -0.577572
3  0.290957 -0.469696  0.463944 -1.142226
4  0.018912  1.773219 -0.279434  0.919145

In [88]:
df.head(1)#gives the first row in the data frame

A         B         C         D
0 -2.527221 -1.045132 -1.622769 -0.757051

In [89]:
df.tail()

A         B         C         D
10  0.323350  1.102024 -0.971712  1.083578
11 -1.322506  0.143315 -0.909598  0.415461
12  0.232145  0.718343  0.761527  0.901154
13  0.421787  0.089221 -0.009078  0.180910
14 -0.107209 -0.735749 -0.476159  1.306162

In [90]:
df.tail(1)#gives the last row in the data frame 

A         B         C         D
14 -0.107209 -0.735749 -0.476159  1.306162

In [91]:
df.tail(2)

A         B         C         D
13  0.421787  0.089221 -0.009078  0.180910
14 -0.107209 -0.735749 -0.476159  1.306162

In [92]:
series_obj=pd.Series(data=np.random.randn(15))

In [93]:
series_obj

0     1.332385
1    -1.329018
2    -0.781845
3    -0.556425
4     0.052222
5    -1.472973
6     0.617473
7     0.313149
8    -2.702182
9    -2.551887
10   -0.826156
11    0.172490
12   -0.477701
13    0.602686
14   -0.539540
dtype: float64

In [94]:
series_obj.head()

0    1.332385
1   -1.329018
2   -0.781845
3   -0.556425
4    0.052222
dtype: float64

In [95]:
series_obj.info()

<class 'pandas.core.series.Series'>
RangeIndex: 15 entries, 0 to 14
Series name: None
Non-Null Count  Dtype  
--------------  -----  
15 non-null     float64
dtypes: float64(1)
memory usage: 252.0 bytes


In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       15 non-null     float64
 1   B       15 non-null     float64
 2   C       15 non-null     float64
 3   D       15 non-null     float64
dtypes: float64(4)
memory usage: 612.0 bytes


In [118]:
data={
    "name":["jobin","nihal","rohith","jerrit"],
    "age":[32,24,53,34],
    "gender":["M","F","M","M"],
    "rating":[4.5,3.5,2.4,5.3]
}

sample_df=pd.DataFrame(data,index=["row1","row2","row3","row4"])
sample_df

name  age gender  rating
row1   jobin   32      M     4.5
row2   nihal   24      F     3.5
row3  rohith   53      M     2.4
row4  jerrit   34      M     5.3

In [98]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    4 non-null      object 
 1   age     4 non-null      int64  
 2   gender  4 non-null      object 
 3   rating  4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 160.0+ bytes


In [99]:
sample_df.describe()

age    rating
count   4.000000  4.000000
mean   35.750000  3.925000
std    12.284814  1.255322
min    24.000000  2.400000
25%    30.000000  3.225000
50%    33.000000  4.000000
75%    38.750000  4.700000
max    53.000000  5.300000

In [100]:
df.describe()

A          B          C          D
count  15.000000  15.000000  15.000000  15.000000
mean    0.075989  -0.048394  -0.086945   0.131204
std     1.255782   0.858574   0.881897   0.881548
min    -2.527221  -1.667361  -1.714255  -1.249833
25%    -0.337027  -0.520109  -0.692878  -0.609761
50%     0.232145  -0.095831   0.080230   0.180910
75%     0.457795   0.347661   0.536724   0.910150
max     2.836031   1.773219   0.968697   1.392849

In [101]:
print(series_obj)

0     1.332385
1    -1.329018
2    -0.781845
3    -0.556425
4     0.052222
5    -1.472973
6     0.617473
7     0.313149
8    -2.702182
9    -2.551887
10   -0.826156
11    0.172490
12   -0.477701
13    0.602686
14   -0.539540
dtype: float64


In [102]:
series_obj.describe()

count    15.000000
mean     -0.543155
std       1.136964
min      -2.702182
25%      -1.077587
50%      -0.539540
75%       0.242819
max       1.332385
dtype: float64

In [123]:
name=['jobin',"nihal","Rohith","dfasfcasv","afvwGWRGV","RGAGAVA","SRBAVA","SAASDVAsdv","ASFBAFD","ARGAG"]
age=[22,223,24,45,65,5,45,5,35,5]
gender=["M","M","F","M","M","F","F","F","F","M"]

sample_dict={
    "Name":pd.Series(name),
    "Age":pd.Series(age),
    "Gender":pd.Series(gender)
    }

table=pd.DataFrame(sample_dict)
table


Name  Age Gender
0       jobin   22      M
1       nihal  223      M
2      Rohith   24      F
3   dfasfcasv   45      M
4   afvwGWRGV   65      M
5     RGAGAVA    5      F
6      SRBAVA   45      F
7  SAASDVAsdv    5      F
8     ASFBAFD   35      F
9       ARGAG    5      M

In [125]:
print(table["Name"].values.dtype)

object


In [113]:
table.head(4)

Name  Age Gender
0      jobin   22      M
1      nihal  223      M
2     Rohith   24      F
3  dfasfcasv   45      M

In [114]:
table.tail(4)

Name  Age Gender
6      SRBAVA   45      F
7  SAASDVAsdv    5      F
8     ASFBAFD   35      F
9       ARGAG    5      M

In [115]:
table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   Gender  10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes


In [116]:
table.describe()

Age
count   10.000000
mean    47.400000
std     64.889992
min      5.000000
25%      9.250000
50%     29.500000
75%     45.000000
max    223.000000

In [5]:
A={
    "name":["jobin","nihal","rohith","jerrit","asdvsdv","adsfdsf","Ssdvdsv","vsadva","sdvsV","dsbV "],
    "age":[32,24,53,34,45,12,12,4,5,45],
    "gender":["M","F","M","M","M","M","F","F","F","M"],
    # "rating":[4.5,3.5,2.4,5.3]
}

sample_df=pd.DataFrame(A)
sample_df

name  age gender
0    jobin   32      M
1    nihal   24      F
2   rohith   53      M
3   jerrit   34      M
4  asdvsdv   45      M
5  adsfdsf   12      M
6  Ssdvdsv   12      F
7   vsadva    4      F
8    sdvsV    5      F
9    dsbV    45      M

In [6]:
print(sample_df["name"].values.dtype)

object


In [10]:
sample_df.loc[1,"name"]

'nihal'

In [17]:
sample_df.loc[[1,3],["name","gender"]]

name gender
1   nihal      F
3  jerrit      M

In [13]:
sample_df.loc[:,["name","age"]]

name  age
0    jobin   32
1    nihal   24
2   rohith   53
3   jerrit   34
4  asdvsdv   45
5  adsfdsf   12
6  Ssdvdsv   12
7   vsadva    4
8    sdvsV    5
9    dsbV    45

In [14]:
sample_df.loc[:,:]

name  age gender
0    jobin   32      M
1    nihal   24      F
2   rohith   53      M
3   jerrit   34      M
4  asdvsdv   45      M
5  adsfdsf   12      M
6  Ssdvdsv   12      F
7   vsadva    4      F
8    sdvsV    5      F
9    dsbV    45      M

In [ ]:
df=pd.DataFrame

In [16]:
sample_df.loc[1:8,"name":"gender"]##here while slicing the last element at the index position of the stop value is also printed

name  age gender
1    nihal   24      F
2   rohith   53      M
3   jerrit   34      M
4  asdvsdv   45      M
5  adsfdsf   12      M
6  Ssdvdsv   12      F
7   vsadva    4      F
8    sdvsV    5      F

In [20]:
#boolean array for filtering
sample_condiiton=sample_df["age"]>30
sample_df.loc[sample_condiiton]

name  age gender
0    jobin   32      M
2   rohith   53      M
3   jerrit   34      M
4  asdvsdv   45      M
9    dsbV    45      M

In [30]:
multiple_condiiton=(sample_df["age"]>30) & (sample_df["gender"]=="M")
sample_df.loc[multiple_condiiton]

name  age gender
0    jobin   32      M
2   rohith   53      M
3   jerrit   34      M
4  asdvsdv   45      M
9    dsbV    45      M

In [36]:
sample_df.loc[sample_df["age"]>=30,"gender"]="Fi"
print(sample_df)

      name  age gender
0    jobin   32     Fi
1    nihal   24      F
2   rohith   53     Fi
3   jerrit   34     Fi
4  asdvsdv   45     Fi
5  adsfdsf   12      M
6  Ssdvdsv   12      F
7   vsadva    4      F
8    sdvsV    5      F
9    dsbV    45     Fi


In [ ]:
#the summary is that yu can filter out the entries in the data frame satisfying the condition using the .loc() method

In [37]:
#ineger position based indexing whith .loc
# the.iloc indexer is used for integer based indexing ,whichb allows you to s
#it is very similar to how string,list,tuple etc.indexing in python

#single integer,list of integer,integer slicing,boolean arrays


In [39]:
import numpy as np

In [41]:
df=pd.DataFrame(data=np.random.randn(8,4),columns=list("ABCD"))
df

A         B         C         D
0 -1.267142  1.544626  1.409334 -0.182911
1 -0.350224  1.135374  0.189841 -1.379312
2 -1.186502 -0.021812  1.645341  1.732266
3 -0.152631 -0.414657  0.288246 -0.540848
4 -1.048478  1.232975  1.117777  0.167005
5  0.109171  0.778517 -0.766444 -0.367931
6  0.562623  1.250993  0.195713 -1.235659
7 -0.072228 -0.524633 -0.323748 -2.199994

In [44]:
df.index=["a","b","c","d","e","f","g","h"]

In [45]:
df

A         B         C         D
a -1.267142  1.544626  1.409334 -0.182911
b -0.350224  1.135374  0.189841 -1.379312
c -1.186502 -0.021812  1.645341  1.732266
d -0.152631 -0.414657  0.288246 -0.540848
e -1.048478  1.232975  1.117777  0.167005
f  0.109171  0.778517 -0.766444 -0.367931
g  0.562623  1.250993  0.195713 -1.235659
h -0.072228 -0.524633 -0.323748 -2.199994

In [47]:
df.loc["a","A"]

np.float64(-1.267141854731403)

In [48]:
df.iloc[0,0]

np.float64(-1.267141854731403)

In [49]:
df.iloc[[0,3,4],[1,3]]

B         D
a  1.544626 -0.182911
d -0.414657 -0.540848
e  1.232975  0.167005

In [53]:
#use iloc method to print entries of laternate rows.
df.iloc[0:4,0:3]

A         B         C
a -1.267142  1.544626  1.409334
b -0.350224  1.135374  0.189841
c -1.186502 -0.021812  1.645341
d -0.152631 -0.414657  0.288246

In [54]:
df.iloc[0::2,0:3]

A         B         C
a -1.267142  1.544626  1.409334
c -1.186502 -0.021812  1.645341
e -1.048478  1.232975  1.117777
g  0.562623  1.250993  0.195713

In [55]:
df.iloc[0:3]

A         B         C         D
a -1.267142  1.544626  1.409334 -0.182911
b -0.350224  1.135374  0.189841 -1.379312
c -1.186502 -0.021812  1.645341  1.732266

In [56]:
df.iloc[::2]

A         B         C         D
a -1.267142  1.544626  1.409334 -0.182911
c -1.186502 -0.021812  1.645341  1.732266
e -1.048478  1.232975  1.117777  0.167005
g  0.562623  1.250993  0.195713 -1.235659

In [103]:
data={"Name":["alice","bob","charlie","david"],
         "Age":[25,45,23,45],
         "Score":[45,85,96,47]}
df=pd.DataFrame(data,index=["first","second","third","fourth"])
print(df)

           Name  Age  Score
first     alice   25     45
second      bob   45     85
third   charlie   23     96
fourth    david   45     47


In [61]:
import pandas as pd
import numpy as np

In [64]:
df.iloc[[0,2]]

Name  Age  Score
first    alice   25     45
third  charlie   23     96

In [98]:
df

Name  Age  Score
first     alice   25     45
second      bob   45     85
third   charlie   23     96
fourth    david   45     47

In [100]:
#mimick boolean fil
condition =df["Age"]>30
print(condition)


first     False
second     True
third     False
fourth     True
Name: Age, dtype: bool


In [101]:
print(np.where(condition))#this will return a tuple of arrays
# the values present in your array are nothing but the row indices for which the given codition is satisfied

(array([1, 3]),)


In [74]:
np.where(condition)[0]

array([1, 3])

In [119]:
df.iloc[[1,3]]

Name  Age  Score
second    bob   45     85
fourth  david   45     47

In [75]:
df.iloc[np.where(condition)[0]]

Name  Age  Score
second    bob   45     85
fourth  david   45     47

In [108]:
df.iloc[np.where(condition)[0],[2]]

Score
second     85
fourth     47

In [82]:
condition2 =df["Score"]>80
df.iloc[np.where(condition2)[0]]

Name  Age  Score
second      bob   45     85
third   charlie   23     96

In [117]:
df.iloc[np.where(condition2)[0],[1]]

Age
second   45
third    23

In [ ]:
df["Age"]>30

first     False
second     True
third     False
fourth     True
Name: Age, dtype: bool

In [86]:
df[df["Age"]>30]

Name  Age  Score
second    bob   45     85
fourth  david   45     47

In [87]:
obj=df["Age"]>30
obj

first     False
second     True
third     False
fourth     True
Name: Age, dtype: bool

In [88]:
np.where(obj)

(array([1, 3]),)

In [89]:
np.where(obj)[0]
df.iloc[np.where(obj)[0]]

Name  Age  Score
second    bob   45     85
fourth  david   45     47

In [97]:
df.iloc[np.where(obj)[0],[0]]

Name
second    bob
fourth  david

In [120]:
condition3 =df["Name"]=="david"
df.iloc[np.where(condition3)[0]]

Name  Age  Score
fourth  david   45     47

In [121]:
# direct indexing whith square brackets :[]
# we can acess a single column,multiple columns(by passing column names as a list)

In [125]:
df[["Name","Age"]]

Name  Age
first     alice   25
second      bob   45
third   charlie   23
fourth    david   45

In [127]:
df[0:2]

Name  Age  Score
first   alice   25     45
second    bob   45     85

SERIES


In [128]:
#a panda Series object has two core components
# 1: Data-- the actual values stores in the Series Object
#2: Index -- The labels or indices that correspomd to each value

In [131]:
obj=pd.Series(["A","B","C"])
obj

0    A
1    B
2    C
dtype: object

In [133]:
obj=pd.Series(["A","B","C"],index=["a","b","c"])
obj

a    A
b    B
c    C
dtype: object

In [142]:
obj=pd.Series(["1","4","5"],index=list("abc"),dtype=np.float64,name="Sample")

print(obj)

a    1.0
b    4.0
c    5.0
Name: Sample, dtype: float64


In [143]:
#python Series objects can be created using python lists,numpy arrays,dictionaries
#you can also cretae an empty Series object

s=pd.Series()

In [144]:
empty_obj=pd.Series(name="Empty_Series_object")

In [146]:
empty_obj

Series([], Name: Empty_Series_object, dtype: object)


In [148]:
string_array= np.array(["A","B","C","D"])
series_obj=pd.Series(string_array)
series_obj

0    A
1    B
2    C
3    D
dtype: object

In [149]:
data_dict={"k":1,"h":2
,"j":3
}

In [150]:
series_obj=pd.Series(data_dict)
series_obj

k    1
h    2
j    3
dtype: int64

In [152]:
series_obj=pd.Series(data_dict,index=["a","b","c"])
series_obj

a   NaN
b   NaN
c   NaN
dtype: float64

In [153]:
series_obj=pd.Series(data_dict,index=["a","b","c","k","j"])
series_obj

a    NaN
b    NaN
c    NaN
k    1.0
j    3.0
dtype: float64

In [155]:
series_obj=pd.Series(7,index=np.arange(7))
series_obj

0    7
1    7
2    7
3    7
4    7
5    7
6    7
dtype: int64