In [ ]:
# before movingon to types of ml we will discuss about 3 terms particulary which are  training data//training set,validation data//validation set and testind data  // tesing set.
# what is training data?

# as discussed erarlier machine learning invlolves the formulation of mthemematichal model which is capable of predicitng output for any given input .

# to arrive apomn a numneric value of the parameters present in your ml model your algotrithm make use of some data in this process and this data is called trainig data and the entire process in termend as model training 

# validation data// model validation

# after learning some values of your parameters yoiu might want to check if your learned model is accurate or not before evaluvating it with completely different set of data.The part or the chunk of your data which you use for this 
# purpose is called validation data / validation set and this entire process is termed as model validation.


# What is Test Data/ Model Testing?

# Before you deploy your model, you need to extensively evaluate whether your model is performing output prediction 
# correctly or not.
# So, this process where you perform your extensive model evaluation is termed as "Model Testing" and the 
# data which is used for this purpose is called test data.Once, the results of your testing process is satisfactory,
# then you go on and deploy your model for real life use cases.





In [ ]:
# Un supervides learning:
# clustering
# dimentionality reduction
# anomaly detection
# association rule based learning


In [ ]:
# Semi-Supervised Learning

# it is a form of learing which is partialy supervised and partially unsupervised.
# It has been developed to overcome the difficulties involved in obtainig the output values for your data .
# you just provide the values for some of your data points and the values for the rest of the data points are automatically assigned.

# Reinforcement learning:

# you provide zero data to your model to train but,you make the agent interact whith the enviornment and learn from the mistakes.
# at the bigining it may be giving wromg ouput but with time and further learning from the mistakes it will optimize itself 
# and will give better results in future




In [ ]:
# based upon how your ml model is utilized at production

# --batch//offline machine learning:

# model gets trained before deployment.and if the new data that comes after deployment which it has to predicy has variations from the parameters which it was trained on .the model has to be brought down to development state and train agin  with the new set of data .this has to be done every time when such situvation occurs.that is the main drawback ok batch machine learning.

# implimented using libraries like scikitlearn,tensor flow-- developed by google,pythorch --developed by meta,pandas,etc
# it is expensive as the data is being sent whole at onc


# -- online machine learning--
# model after deployment is continiously being trained with the updated data.with libraries like 
# it is cost effective scince the data is sent in batches.



In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
b=np.array([[1,2,3,4],[2,3,4,56],[67,5,5,6]])
print(b)
print(b.ndim)

[[ 1  2  3  4]
 [ 2  3  4 56]
 [67  5  5  6]]
2


In [16]:
#get shape
a.shape
b.shape

(3, 4)

In [18]:
#get type
b.dtype

dtype('int64')

Acesing /changing specific elements rows colums etc


In [19]:
a=np.array([[1,2,3,4,5,6,7],[12,34,56,8,32,57,67]])
print(a)

[[ 1  2  3  4  5  6  7]
 [12 34 56  8 32 57 67]]


In [21]:
print(a[1,3])

8


In [22]:
#get a specific row
a[1,:]

array([12, 34, 56,  8, 32, 57, 67])

In [25]:
# get a specific column
a[:,1]

array([ 2, 34])

In [24]:
#accessing a littile more specific
a[0,1:6]

array([2, 3, 4, 5, 6])

In [29]:
x=np.arange(6)
x=x.reshape(2,3)
print(x)

[[0 1 2]
 [3 4 5]]


In [30]:
x.sum()

np.int64(15)

In [31]:
x.sum(axis=0)#note if axis=0 means along x axis

array([3, 5, 7])

In [32]:
x.sum(axis=1) # axis=1 means alomg y axis

array([ 3, 12])

In [33]:
x.min(axis=0)

array([0, 1, 2])

In [34]:
x.max(axis=1)

array([2, 5])

In [35]:
#argmax(),argmin(),argsort()
d1=np.array([1,4,8,3,6,8,32,2])
d1.argmax()

np.int64(6)

In [36]:
d1.argmin()

np.int64(0)

In [37]:
d1.argsort()

array([0, 7, 3, 1, 4, 2, 5, 6])